name: Get full info

on:
  push:
    branches:
      - main

jobs:
  generate:
    uses: symbioticfi/metadata-validation-scripts/.github/workflows/full-info.yml@e3824a8ec94aa353bb4f5828f490688e84f51721 # main
